name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.5

      - uses: subosito/flutter-action@v2.16.0

      - run: flutter build web --release --web-renderer canvaskit --base-href "/equran_app/"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          personal_token: ${{ secrets.DEPLOY_KEY }}
