name: "Produce New Tag"  
on: 
 push:
   branches:
     - main

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2

     - name: Get Flutter version (Optional) 
       id: get_flutter_version       
       uses: its404/get-flutter-version@v1.0.0

     - name: Output Flutter version (Optional)
       run: echo 'version_number:' ${{ steps.get_flutter_version.outputs.version_number }} ' build_number:' ${{ steps.get_flutter_version.outputs.build_number }}

     - name: Get latest tag pushed
       id: tag
       uses: oprypin/find-latest-tag@v1.1.2
       with:
        repository: ya27hw/equran_app
        releases-only: true
     - run: echo "${{ steps.tag.outputs.tag }}"

     - name: Compare Versions and Create Tag (Modified)
       if: ${{ "v${{steps.get_flutter_version.outputs.version_number}}" > steps.tag.outputs.tag }}  # Modified Condition
       run: |
         VERSION=${{ steps.get_flutter_version.outputs.version_number }} 
         git tag -a $VERSION -m "Automatic tag for version $VERSION"
         git push origin $VERSION
